### ISSUE TITLE
Problem #2 with content elements in EXT:news

### ISSUE THREAD

**Issue by SventB** [thieleundklose/tk-typo3-autotranslate#16]
There's bug with TYPO3 v10 and feature "Content elements" of EXT:news:

![image](https://github.com/thieleundklose/autotranslate/assets/2690489/38418f9f-bbed-4c83-82fd-6b20a4286856)

When saving newly added content element in EXT:news records, an error is thrown:

```
Doctrine\DBAL\Exception\SyntaxErrorException

An exception occurred while executing 'UPDATE `tt_content` SET WHERE uid=12627': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE uid=12627' at line 1
```

This can be fixed here (https://github.com/thieleundklose/autotranslate/blob/main/Classes/Utility/Translator.php#L165) by changing the code to:

```
            if ($translatedColumns) {
                Records::updateRecord($table, $localizedUid, $translatedColumns);
            }
```

**Comment by mikezimmer-tuk** [comment]
Hi Sven, i think this issue is fixed already. Is it possible that you can test it again? Otherwise i would close this Issue in 7 days.
Best regards, Mike

**Comment by SventB** [comment]
This error message is fixed, but when using this feature ("Content elements in EXT:news"), the English content element is showing up in page module:

![image](https://github.com/thieleundklose/autotranslate/assets/2690489/77a6b08f-e83a-4089-8a25-b385b3676847)

This is only happening with installed EXT:autotranslate.

The German content element isn't shown there. When you compare the records in tt_content, you will see that in column "tx_news_related_news" a value is missing for the English content element, I guess this is the problem.

**Comment by mikezimmer-tuk** [comment]
@SventB Can you please send me your site config regarding the language settings. And the order in which you created the news/content element? Then I could take a closer look at the problem.

**Comment by SventB** [comment]
I can't reproduce this any more... :-o

But error message `Localization failed: there already are localizations (13413) for language 1 of the "tt_content" record 13412` is shown, when I do this:

1. Create news record in default language
2. Save news record
3. Create content element in news record
4. Save news record
5. Check which records have been created in tt_content: There is already a translation for the tt_content element!
6. Activate checkbox "English" in field "Translate automatically to selected languages" (all these checkboxes aren't checked by default)
7. Save news record

My autotranslate settings are to translate tt_content by default but do **not** translate tx_news by default:

![image](https://github.com/thieleundklose/autotranslate/assets/2690489/c04a614a-6e22-4111-b49f-fd890e6cc174)


> Can you please send me your site config regarding the language settings.

```
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: '...'
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    base: '...'
    typo3Language: en
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: '...'
    navigationTitle: English
    hreflang: en-US
    direction: ''
    fallbackType: strict
    fallbacks: '0'
    flag: en-us-gb
    languageId: 1
    deeplTargetLang: EN-GB
  -
    title: Österreichisch
    enabled: true
    base: '...'
    typo3Language: de
    locale: de_AT.UTF-8
    iso-639-1: de
    websiteTitle: '...'
    navigationTitle: Österreichisch
    hreflang: de-AT
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: at
    languageId: 5
  -
    title: Schweizerisch
    enabled: true
    base: '...'
    typo3Language: de
    locale: de_CH.UTF-8
    iso-639-1: de
    websiteTitle: '...'
    navigationTitle: Schweizerisch
    hreflang: de-CH
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: ch
    languageId: 6
```
